version: '3.7'

x-rails-base: &rails-base
  build:
    context: .
    dockerfile: docker/Dockerfile.local
  working_dir: /var/www/app
  volumes:
    - auth0-react-playground-web-src:/var/www/app:nocopy
    - bundle:/usr/local/bundle
services:
  db:
    image: mysql:5.7.33
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT:-5001}:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Tokyo'
  web:
    <<: *rails-base
    tty: true
    stdin_open: true
    command: /bin/sh -c 'rm -f tmp/pids/server.pid && ./bin/rails server -p 3000 -b 0.0.0.0'
    ports:
      - ${WEB_PORT:-5000}:3000
    depends_on:
      - db
    env_file:
      - '.env.development.local'
volumes:
  bundle:
  db:
  auth0-react-playground-web-src:
    external: true
