FROM ruby:2.7.2-slim

ENV RAILS_ROOT /var/www/app
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

RUN apt-get update -qq && \
    apt-get install -y build-essential fonts-noto-cjk curl default-libmysqlclient-dev default-mysql-client imagemagick git && \
    rm -rf /var/lib/apt/lists/*

# Node
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs && \
    rm -rf /var/lib/apt/lists/*

WORKDIR $RAILS_ROOT
